language: go

go:
  - 1.11.5

# Only clone the most recent commit.
git:
  depth: 1

install:
  #- test ! -d /home/travis/gopath/src/github.com/jkerry && mv /home/travis/gopath/src/github.com/* /home/travis/gopath/src/github.com/jkerry
  - mv /home/travis/gopath/src/github.com/jkerry/nagios-foundation /home/travis/gopath/src/github.com/jkerry/nagiosfoundation
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure -v

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./... && bash <(curl -s https://codecov.io/bash)
  - make package
