language: go

go:
  - 1.12.0

# Only clone the most recent commit.
git:
  depth: 1

install:
  #- test ! -d /home/travis/gopath/src/github.com/ncr-devops-platform && mv /home/travis/gopath/src/github.com/* /home/travis/gopath/src/github.com/ncr-devops-platform
  - mv /home/travis/gopath/src/github.com/ncr-devops-platform/nagios-foundation /home/travis/gopath/src/github.com/ncr-devops-platform/nagiosfoundation
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure -v

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./... && bash <(curl -s https://codecov.io/bash)
  - make package
