products:
  check_available_memory:
    build:
      main-pkg: 'cmd/check_available_memory'
      os-archs:
        - os: windows
          arch: amd64
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_cpu:
    build:
      main-pkg: 'cmd/check_cpu'
      os-archs:
        - os: windows
          arch: amd64
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64