products:
  check_available_memory:
    build:
      main-pkg: 'cmd/check_available_memory'
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_cpu:
    build:
      main-pkg: 'cmd/check_cpu'
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_performance_counter:
    build:
      main-pkg: 'cmd/check_performance_counter'
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_service:
    build:
      main-pkg: 'cmd/check_service'
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_user_group:
    build:
      main-pkg: 'cmd/check_user_group'
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_process:
    build:
      main-pkg: 'cmd/check_process'
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
